### ISSUE TITLE
The background image is too big to load 

### ISSUE THREAD

**Issue by sasankaweera123** [ravi-aratchige/ravi-aratchige.github.io#1]
# Issue 
The background image is too big to load 

## Options:
 - Change the background image 
 - Update the image as SVG in HTML
 - Create the image using CSS

## Aditional Info 

- Personally, I recommend you use another background image because the current one doesn't match the glass effect ( your content can't see  clearly )

**Comment by ravi-aratchige** [comment]
Thanks for bringing up the issue! I have changed the background image temporarily to a smaller image... will be moving to an SVG or CSS based background soon. The new image also ensures that the content on the glass overlay is now more clearly visible.

- Ravi
